### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by stone212** [parity-js/shell#150]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 0.2.7
> - **Parity UI version**: 1.10.x
> - **Operating system**: Linux
> - **Installed via**: deb
> - **Fully synchronized**: yes
> - **Network**: private
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After creating an SSH tunnel to my server using these instructions (https://wiki.parity.io/Wallet-Remote-Access.html) the tunnel looks good.  I get:

> debug1: channel 4: free: direct-tcpip: listening port 8546 for 127.0.0.1 port 8546, connect from 127.0.0.1 port 57626 to 127.0.0.1 port 8546, nchannels 4

The Parity UI comes up but an error message requires me to click OK.  Screenshot attached.

Please note that this error does not prevent me from using the Parity UI.  I click "OK" and I am in the familiar UI and it seems to work normally.

**Comment by Tbaut** [comment]
Thanks for the report.

**Comment by amaurymartiny** [comment]
Hey @stone212! Do you still have the screenshot by any chance?

**Comment by stone212** [comment]
@amaurymartiny Here you are.
[
![parityjserror](https://user-images.githubusercontent.com/26020999/42193568-a1104a60-7e5e-11e8-9ba6-ddca37aa4b9c.png)
](url)

**Comment by axelchalon** [comment]
should be fixed with https://github.com/parity-js/shell/pull/144/commits/a76cfef91c6cd6f6d2d050c57ea9298e237d7972

**Comment by axelchalon** [comment]
closing for now; should be fixed since Parity UI v0.3.0
let us know if you still have this error

**Comment by stone212** [comment]
@axelchalon I still have this (well a very similar) error with Parity UI 0.34.  Screenshot of current error attached.
![34error](https://user-images.githubusercontent.com/26020999/44186586-d4193700-a109-11e8-9ba6-12dcedd04f49.png)
